name: Docker Build ⚓

on:
  workflow_dispatch:

jobs:
  disabled:
    name: Docker build disabled
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "Docker workflow is disabled."
