[project]
site_name = "istSOS4 SensorThingsAPI Workshop"
site_description = "A hands-on workshop for learning IoT sensor data management with istSOS4 and the OGC SensorThings API."
site_author = "the istSOS4 Workshop Team"
site_url = "https://istsos.github.io/istsos4-workshop"
repo_url = "https://github.com/istSOS/istsos4-workshop"
docs_dir = "docs"
edit_uri = "edit/main/web/docs"
copyright = """
    Copyright (c) 2024 the istSOS4 Workshop Team - <a href="#__consent">Change cookie settings</a><br/>
    This website is released under the <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license</a>"
"""
extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
]

extra_css = ["stylesheets/extra.css"]

nav = [
    {"Getting started" = [
        "getting_started/intro.md",
        "getting_started/installation.md",
        "getting_started/docker.md",
        "getting_started/configuration.md",
        "getting_started/authorization.md"
    ]},
    {"Key concepts" = [
        "concepts/sensing.md",
        "concepts/interoperability.md",
        "concepts/sta.md",
        "concepts/authentication.md",
        "concepts/temporal_query.md",
        "concepts/open_science.md",
        "concepts/traveltime_extension.md"
    ]},
    {"Tutorial Basic" = [
        "basic/swagger.md",
        "basic/authorization.md",
        "basic/traveltime.md",
        "basic/sensors.md",
        "basic/ui.md",
        "basic/view_data.md"
    ]},
    {"Tutorial Advanced" = [
        "advanced/00_Introduction.md",
        "advanced/01_Authorization.md",
        "advanced/02_STA_Entities.md",
        "advanced/03_STA_Observations.md",
        "advanced/04_Time_Travel.md"
    ]},
    {"About" = [
        {"Team (c)" = "about/team.md"},
        "about/version.md"
    ]}
]

[project.theme]
logo = "images/istsos_bars.png"
favicon = "images/favicon.ico"
features = [
    "navigation.tabs",
    "navigation.tabs.sticky"
]

[project.markdown_extensions.md_in_html]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.attr_list]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.zensical.extensions.glightbox]

[project.theme.icon.admonition]
technology = "lucide/cpu"