[project]
site_name = "istSOS4 SensorThingsAPI Workshop"
site_description = "A hands-on workshop for learning IoT sensor data management with istSOS4 and the OGC SensorThings API."
site_author = "the istSOS4 Workshop Team"
copyright = "Copyright (c) 2024 the istSOS4 Workshop Team<br/>This website is released under the <a href=\"https://creativecommons.org/licenses/by/4.0\">Creative Commons Attribution 4.0 International (CC BY 4.0) license</a>"
site_url = "https://istsos.github.io/istsos4-workshop"
repo_url = "https://github.com/istSOS/istsos4-workshop"
docs_dir = "docs"
edit_uri = "edit/main/web/docs"

nav = [
    {"Home" = "index.md"},
    {"Docker installation" = "docker.md"}
]
